// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stayzee.Infrastructure.Data;

#nullable disable

namespace Stayzee.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503123636_Seed data for Rooms")]
    partial class SeeddataforRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stayzee.Domain.Entities.Rooms", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecificDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Villa_Id")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("Villa_Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 101,
                            SpecificDetails = "Ocean view, private balcony",
                            VillaName = "Royal Villa",
                            Villa_Id = 1
                        },
                        new
                        {
                            RoomId = 102,
                            SpecificDetails = "Ground floor, garden access",
                            VillaName = "Royal Villa",
                            Villa_Id = 1
                        },
                        new
                        {
                            RoomId = 201,
                            SpecificDetails = "Direct beach access",
                            VillaName = "Beachfront Villa",
                            Villa_Id = 2
                        },
                        new
                        {
                            RoomId = 202,
                            SpecificDetails = "Upper floor, sea view",
                            VillaName = "Beachfront Villa",
                            Villa_Id = 2
                        },
                        new
                        {
                            RoomId = 301,
                            SpecificDetails = "Private pool, king bed",
                            VillaName = "Luxury Pool Villa",
                            Villa_Id = 3
                        },
                        new
                        {
                            RoomId = 302,
                            SpecificDetails = "Jacuzzi, garden view",
                            VillaName = "Luxury Pool Villa",
                            Villa_Id = 3
                        });
                });

            modelBuilder.Entity("Stayzee.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 3, 18, 6, 35, 315, DateTimeKind.Local).AddTicks(3895),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 3, 18, 6, 35, 316, DateTimeKind.Local).AddTicks(9237),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 5, 3, 18, 6, 35, 316, DateTimeKind.Local).AddTicks(9252),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("Stayzee.Domain.Entities.Rooms", b =>
                {
                    b.HasOne("Stayzee.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("Villa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
